# Generated by Django 5.2.1 on 2025-06-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_app', '0002_alter_company_address_alter_company_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='description',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='status',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='type',
        ),
        migrations.AddField(
            model_name='organization',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='pharma_app.doctor'),
        ),
    ]
