# Generated by Django 5.2.1 on 2025-06-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_app', '0003_rename_description_schedule_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='schedule',
            name='type',
            field=models.CharField(choices=[('visit', 'Visit'), ('meeting', 'Meeting'), ('training', 'Training'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
